import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "O2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-3xl mx-auto text-slate-900">
          <header className="p-6 border-b flex justify-between bg-blue-300 rounded-br-lg rounded-bl-lg items-center">
            <Link href="/" className="text-2xl font-bold text-white">Sistema de Gestão de Estoque</Link>
            <div>
              <Link href="/pages/create" className="bg-slate-100 grid place-items-center py-2 px-4 rounded-full font-bold shadow-md">Adicionar</Link>
              <Link href="/pages/relatorio" className="bg-slate-100 grid place-items-center py-2 px-4 rounded-full font-bold shadow-md mt-2">Relatorios</Link>
            </div>
          </header>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}